server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/crudCourses?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
